# ansible/inventory/hosts.yml
all:
  hosts:
    monitoring:
      ansible_host: 192.168.15.201
      ansible_user: ubuntu

    dev:
      ansible_host: 192.168.15.202
      ansible_user: ubuntu

    homolog:
      ansible_host: 192.168.15.203
      ansible_user: ubuntu
