# ansible/inventory/hosts.yml
all:
  hosts:
    CORE-K3S:
      ansible_host: 192.168.15.92
      ansible_user: homelab

    ubuntu-server:
      ansible_host: 192.168.15.64
      ansible_user: ubuntu-server

    homelab-monitoring:
      ansible_host: 192.168.15.XXX   # atualizar após terraform apply
      ansible_user: homelab

    homelab-dev:
      ansible_host: 192.168.15.XXX   # atualizar após terraform apply
      ansible_user: homelab
