# ansible/inventory/hosts.yml
all:
  # vars:
  #   k3s_version: v1.28.5+k3s1 # Exemplo de versão do k3s
    hosts:

      CORE-K3S:
        ansible_host: 192.168.15.92
        ansible_user: homelab

      ubuntu-server:
        ansible_host: 192.168.15.64
        ansible_user: ubuntu-server