modules:
  icmp_ping:
    prober: icmp
    timeout: 5s

  tcp_port_check:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"  # Ou "ip6" se preferir IPv6
      ip_protocol_fallback: true
