---
- name: Install dev utils (amd64)
  apt:
    name:
      - build-essential
      - vim
      - tmux
      - sshuttle
      - neovim
      - git
    state: present
    update_cache: yes
  tags:
    - apt
  when: ansible_architecture == "x86_64"
  # become: true  

- block:
    - name: Remove bullseye-backports entries from sources.list
      become: true
      replace:
        path: /etc/apt/sources.list
        regexp: '^(deb .*bullseye-backports.*)$'
        replace: '# \1'
      ignore_errors: true

    - name: Update APT cache
      apt:
        update_cache: yes
      ignore_errors: true

    - name: Install dev utils (arm64)
      apt:
        name:
          - vim
          - tmux
          - sshuttle
          - nano
          - git
        state: present
      tags:
        - apt
  when: ansible_architecture == "aarch64"
